//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yotalab.PlanningPoker.BlazorServerSide.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yotalab.PlanningPoker.BlazorServerSide.Resources.UIResources", typeof(UIResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Moderator.
        /// </summary>
        public static string AddModeratorButton {
            get {
                return ResourceManager.GetString("AddModeratorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to My Sessions.
        /// </summary>
        public static string BackToMySessionsButton {
            get {
                return ResourceManager.GetString("BackToMySessionsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average: {0}.
        /// </summary>
        public static string ChartAverage {
            get {
                return ResourceManager.GetString("ChartAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score {0} - {1} (votes: {2}).
        /// </summary>
        public static string ChartVoteSummary {
            get {
                return ResourceManager.GetString("ChartVoteSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Session.
        /// </summary>
        public static string CreateSession {
            get {
                return ResourceManager.GetString("CreateSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        public static string EditParticipantInfoButton {
            get {
                return ResourceManager.GetString("EditParticipantInfoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to submit profile changes, try again later..
        /// </summary>
        public static string EditParticipantInfoDialogAvatarSubmitError {
            get {
                return ResourceManager.GetString("EditParticipantInfoDialogAvatarSubmitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upload image, try again later..
        /// </summary>
        public static string EditParticipantInfoDialogAvatarUploadError {
            get {
                return ResourceManager.GetString("EditParticipantInfoDialogAvatarUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image size should not be larger than {0} kbyte.
        /// </summary>
        public static string EditParticipantInfoDialogMaxAvatarSize {
            get {
                return ResourceManager.GetString("EditParticipantInfoDialogMaxAvatarSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string EditParticipantInfoDialogNameLabel {
            get {
                return ResourceManager.GetString("EditParticipantInfoDialogNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing profile.
        /// </summary>
        public static string EditParticipantInfoDialogTitle {
            get {
                return ResourceManager.GetString("EditParticipantInfoDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically stop the session and show votes when all participants have voted.
        /// </summary>
        public static string EditSessionDialogAutoStopHint {
            get {
                return ResourceManager.GetString("EditSessionDialogAutoStopHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic stop the session.
        /// </summary>
        public static string EditSessionDialogAutoStopLabel {
            get {
                return ResourceManager.GetString("EditSessionDialogAutoStopLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Name.
        /// </summary>
        public static string EditSessionDialogNameLabel {
            get {
                return ResourceManager.GetString("EditSessionDialogNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session name cannot be empty.
        /// </summary>
        public static string EditSessionDialogNameRequired {
            get {
                return ResourceManager.GetString("EditSessionDialogNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing session.
        /// </summary>
        public static string EditSessionDialogTitle {
            get {
                return ResourceManager.GetString("EditSessionDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh page.
        /// </summary>
        public static string ErrorBoundaryRefreshLink {
            get {
                return ResourceManager.GetString("ErrorBoundaryRefreshLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, try.
        /// </summary>
        public static string ErrorBoundaryText {
            get {
                return ResourceManager.GetString("ErrorBoundaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude.
        /// </summary>
        public static string ExcludeParticipantButton {
            get {
                return ResourceManager.GetString("ExcludeParticipantButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting has ended.
        /// </summary>
        public static string FinishedSessionState {
            get {
                return ResourceManager.GetString("FinishedSessionState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string FinishSessionButton {
            get {
                return ResourceManager.GetString("FinishSessionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string InitialSessionButton {
            get {
                return ResourceManager.GetString("InitialSessionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface Language.
        /// </summary>
        public static string InterfaceLanguage {
            get {
                return ResourceManager.GetString("InterfaceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string JoinButton {
            get {
                return ResourceManager.GetString("JoinButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Session.
        /// </summary>
        public static string LeaveSessionButton {
            get {
                return ResourceManager.GetString("LeaveSessionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Sessions.
        /// </summary>
        public static string MySessions {
            get {
                return ResourceManager.GetString("MySessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nameless.
        /// </summary>
        public static string NamelessParticipantName {
            get {
                return ResourceManager.GetString("NamelessParticipantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Session.
        /// </summary>
        public static string NewSessionName {
            get {
                return ResourceManager.GetString("NewSessionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not a participant of the session &apos;{0}&apos;.
        /// </summary>
        public static string NotParticipantHint {
            get {
                return ResourceManager.GetString("NotParticipantHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No voting is held.
        /// </summary>
        public static string NotStartedSessionState {
            get {
                return ResourceManager.GetString("NotStartedSessionState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants: {0}.
        /// </summary>
        public static string ParticipantsCount {
            get {
                return ResourceManager.GetString("ParticipantsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Moderator.
        /// </summary>
        public static string RemoveModeratorButton {
            get {
                return ResourceManager.GetString("RemoveModeratorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveSession {
            get {
                return ResourceManager.GetString("RemoveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing session.
        /// </summary>
        public static string RemoveSessionDialogTitle {
            get {
                return ResourceManager.GetString("RemoveSessionDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session &lt;b&gt;&apos;{0}&apos;&lt;/b&gt; cannot be restored after deletion..
        /// </summary>
        public static string RemoveSessionDialogWarning {
            get {
                return ResourceManager.GetString("RemoveSessionDialogWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string RestartSessionButton {
            get {
                return ResourceManager.GetString("RestartSessionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        public static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session not exists.
        /// </summary>
        public static string SessionNotExists {
            get {
                return ResourceManager.GetString("SessionNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not participating in any session yet.
        /// </summary>
        public static string SessionsEmpty {
            get {
                return ResourceManager.GetString("SessionsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting has begun....
        /// </summary>
        public static string StartedSessionState {
            get {
                return ResourceManager.GetString("StartedSessionState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartSessionButton {
            get {
                return ResourceManager.GetString("StartSessionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting stopped.
        /// </summary>
        public static string StoppedSessionState {
            get {
                return ResourceManager.GetString("StoppedSessionState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string StopSessionButton {
            get {
                return ResourceManager.GetString("StopSessionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voted: {0}/{1}.
        /// </summary>
        public static string VotedParticipantsCount {
            get {
                return ResourceManager.GetString("VotedParticipantsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting is underway.
        /// </summary>
        public static string VotingInProcess {
            get {
                return ResourceManager.GetString("VotingInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make estimating Agile projects simple and fun..
        /// </summary>
        public static string WellcomeSubtitle {
            get {
                return ResourceManager.GetString("WellcomeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear and simple planning!.
        /// </summary>
        public static string WellcomeTitle {
            get {
                return ResourceManager.GetString("WellcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You a moderator.
        /// </summary>
        public static string YouModerator {
            get {
                return ResourceManager.GetString("YouModerator", resourceCulture);
            }
        }
    }
}
