//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yotalab.PlanningPoker.BlazorServerSide.Areas.Identity.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IdentityUIResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IdentityUIResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yotalab.PlanningPoker.BlazorServerSide.Areas.Identity.Resources.IdentityUIResourc" +
                            "es", typeof(IdentityUIResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New to Agile Poker?.
        /// </summary>
        public static string NotRegisteredQuestion {
            get {
                return ResourceManager.GetString("NotRegisteredQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A password reset email has been sent to the email address &apos;{0}&apos;..
        /// </summary>
        public static string PasswordRecoverySentDetails {
            get {
                return ResourceManager.GetString("PasswordRecoverySentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Recovery.
        /// </summary>
        public static string PasswordRecoveryTitle {
            get {
                return ResourceManager.GetString("PasswordRecoveryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPasswordButton {
            get {
                return ResourceManager.GetString("ResetPasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reset your password by &lt;a href=&apos;{0}&apos;&gt;clicking here&lt;/a&gt;..
        /// </summary>
        public static string ResetPasswordEmailBody {
            get {
                return ResourceManager.GetString("ResetPasswordEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPasswordEmailTitle {
            get {
                return ResourceManager.GetString("ResetPasswordEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset.
        /// </summary>
        public static string ResetPasswordSuccess {
            get {
                return ResourceManager.GetString("ResetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPasswordTitle {
            get {
                return ResourceManager.GetString("ResetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed sign in attempt.
        /// </summary>
        public static string SignInAttemptFailed {
            get {
                return ResourceManager.GetString("SignInAttemptFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignInButton {
            get {
                return ResourceManager.GetString("SignInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in, please.
        /// </summary>
        public static string SignInTitle {
            get {
                return ResourceManager.GetString("SignInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed sign in attempt using an external account.
        /// </summary>
        public static string SignInWithAttemptFailed {
            get {
                return ResourceManager.GetString("SignInWithAttemptFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient permissions to receive the user&apos;s email.
        /// </summary>
        public static string SignInWithAttemptFailedNotEnoughPermissions {
            get {
                return ResourceManager.GetString("SignInWithAttemptFailedNotEnoughPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed sign in attempt using an external account: {0}.
        /// </summary>
        public static string SignInWithAttemptFailedRemoteError {
            get {
                return ResourceManager.GetString("SignInWithAttemptFailedRemoteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with {0}.
        /// </summary>
        public static string SignInWithButton {
            get {
                return ResourceManager.GetString("SignInWithButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SignUpButton {
            get {
                return ResourceManager.GetString("SignUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your account by &lt;a href=&apos;{0}&apos;&gt;clicking here&lt;/a&gt;..
        /// </summary>
        public static string SignUpConfirmationEmailBody {
            get {
                return ResourceManager.GetString("SignUpConfirmationEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up Confirmation.
        /// </summary>
        public static string SignUpConfirmationEmailTitle {
            get {
                return ResourceManager.GetString("SignUpConfirmationEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email confirmation error..
        /// </summary>
        public static string SignUpConfirmationFailed {
            get {
                return ResourceManager.GetString("SignUpConfirmationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email has been sent to the email address &apos;{0}&apos; to confirm registration..
        /// </summary>
        public static string SignUpConfirmationSentDetails {
            get {
                return ResourceManager.GetString("SignUpConfirmationSentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email has been confirmed. Thank you for choosing us!.
        /// </summary>
        public static string SignUpConfirmationSuccess {
            get {
                return ResourceManager.GetString("SignUpConfirmationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up Confirmation.
        /// </summary>
        public static string SignUpConfirmationTitle {
            get {
                return ResourceManager.GetString("SignUpConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed sign up, please repeat later.
        /// </summary>
        public static string SignUpFailed {
            get {
                return ResourceManager.GetString("SignUpFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        public static string SignUpLink {
            get {
                return ResourceManager.GetString("SignUpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a New User.
        /// </summary>
        public static string SignUpTitle {
            get {
                return ResourceManager.GetString("SignUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not confirmed your email.
        /// </summary>
        public static string UserNotConfirmEmail {
            get {
                return ResourceManager.GetString("UserNotConfirmEmail", resourceCulture);
            }
        }
    }
}
